project:
  type: website

website:
  site-url: https://shlokvaibhav.github.io/RTR_LS/
  title: "Rail-to-Rail Input Amplifiers"
  sidebar:
  - id: analog
    style: docked
    search: true
    contents:
    - section: "Strong Inversion"
      contents:
        - text: "Electronic Zener"
          href: RTR/Zener.qmd
        - text: "Crude 4x Mirror"
          href: RTR/Crude4xmirror.qmd
    - section: "Weak Inversion"
      contents:
        - text: "Min Max Selector"
          href: RTR/Min_Max_Selector.qmd      - 
    - section: "Sub-1V"
      contents:
        - text: "Dynamic Common Mode LS"
          href: RTR/Sub-1V-Dynamic-LS.qmd      - 
 
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



